name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      - name: Set up Go
        uses: actions/setup-go@latest
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@latest
        with:
          version: latest
