name: Release
on:
  push:
    tags:
      - v*
jobs:
  golangci:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      - name: Set up Go
        uses: actions/setup-go@latest
        with:
          go-version: 1.19
      - name: Build
        run: make build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./bin/*

