name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      - name: Set up Go
        uses: actions/setup-go@latest
        with:
          go-version: 1.19
      - name: Test
        run: make test
